# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/conditional-text
conditional-text:
  actionbar:
    priority_1:
      text: '%np_background_other_actionbar%' # hides the money hud when a player rides something or dives in water
      conditions:
        condition_or:
          type: "||"
          refresh-interval: 1
          value:
            condition_passenger:
              type: is-passenger
              refresh-interval: 1
              value: true
            condition_air:
              type: "!="
              refresh-interval: 1
              value:
                value1: '%player_remaining_air%'
                value2: "300"
            condition_gamemode:
              type: "!gamemode"
              refresh-interval: 1
              value: survival
    priority_2:
      text: '%np_static_money_hud%%np_offset_-179%%np_static_other_actionbar%' # displays the money hud + other plugin's actionbar message
      conditions:
        condition_other_actionbar:
          type: "!equals"
          refresh-interval: 1
          value:
            value1: '%np_actionbar%'
            value2: ""
    priority_3:
      text: '%np_static_money_hud%' # displays the money hud only
  weather:
    priority_1:
      text: 'Sunny'
      conditions:
        weather:
          - clear
    priority_2:
      text: 'Rainy'
      conditions:
        weather:
          - rain
    priority_3:
      text: 'Thunder'
      conditions:
        weather:
          - thunder

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/background-nameplate-bubble-text
bubble-text:
  chat:
    bubble: chat_1
    text: '<black>Nice to meet you!</black>'
    left-margin: 1
    right-margin: 1

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/background-nameplate-bubble-text
nameplate-text:
  halloween:
    nameplate: halloween
    text: '<gradient:#FFD700:#FFA500:#FFD700>Today is Halloween! Trick or treat!</gradient>'
    left-margin: 1
    right-margin: 1

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/background-nameplate-bubble-text
background-text:
  location:
    background: bedrock_1
    text: '%np_image_compass% %np_shift_location%'
    shadow: false
    left-margin: 1
    right-margin: 1
  time:
    background: bedrock_1
    text: '%np_image_clock% %np_shift_time%'
    shadow: false
    left-margin: 1
    right-margin: 1
  weather:
    background: bedrock_1
    text: '%np_image_weather% %np_shift_weather%'
    shadow: false
    left-margin: 1
    right-margin: 1
  hello:
    background: bedrock_1
    text: '%np_image_bubble% %np_shift_hello%'
    shadow: false
    left-margin: 1
    right-margin: 1
  update:
    background: bedrock_1
    text: '%np_image_bell% %np_shift_update%'
    shadow: false
    left-margin: 1
    right-margin: 1
  other_actionbar:
    background: bedrock_2
    text: '%np_actionbar%'
    shadow: false
    left-margin: 1
    right-margin: 1

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/static-text
static-text:
  money_hud:
    position: right
    text: '%np_image_coin% %np_shift_money%'
    value: 180
  other_actionbar:
    position: middle
    text: "%np_background_other_actionbar%"
    value: 180

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/descent-text
shift-text:
  player_name:
    text: "%player_name%"
    font: shift_0
  location:
    text: "Your Location: %np_switch_world% (%player_x%,%player_y%,%player_z%)"
    font: shift_1
  time:
    text: "Time: %np_time_12%"
    font: shift_1
  weather:
    text: "Weather: %np_conditional_weather%"
    font: shift_1
  update:
    text: "A newer version of CustomNameplates is available!"
    font: shift_1
  hello:
    text: "Hello 여보세요 你好 こんにちは, Thanks for using CustomNameplates"
    font: shift_1
  money:
    text: "%vault_eco_balance%"
    font: shift_2

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/switch-text
switch-text:
  nameplate_color_prefix:
    switch: "%np_equipped_nameplate%"
    default: ""
    case:
      'halloween': "<gradient:#FF0000:#000000:%np_gradient_3%>"
      'hutao': "<gradient:#FFFFFF:#FF4500:%np_gradient_3%>"
      'rabbit': "<gradient:#FFFFFF:#DB7093:%np_gradient_3%>"
      'starsky': "<gradient:#FFFFF0:#696969:%np_gradient_3%>"
      'trident': "<gradient:#E1FFFF:#008B8B:%np_gradient_10%>"
      'egg': "<gradient:#FFFFFF:#FFA500:%np_gradient_5%>"
      'xmas': "<WHITE>"
      'angel': "<#8B4513>"
      'sign': "<BLACK>"
      'banner': "<WHITE>"
      'enter': "<WHITE>"
  nameplate_color_suffix:
    switch: "%np_equipped_nameplate%"
    default: ""
    case:
      'halloween': "</gradient>"
      'hutao': "</gradient>"
      'rabbit': "</gradient>"
      'starsky': "</gradient>"
      'trident': "</gradient>"
      'egg': "</gradient>"
      'xmas': "</WHITE>"
      'angel': "</#8B4513>"
      'sign': "</BLACK>"
      'banner': "</WHITE>"
      'enter': "</WHITE>"
  world:
    switch: '%player_world%'
    case:
      'world': "<green>Overworld</green>"
      'world_nether': "<red>The Nether</red>"
      'world_the_end': "<red>The End</red>"
    default: "<gray>Unknown world</gray>"

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/vanilla-hud
vanilla-hud:
  stamina_hud:
    reverse: true
    images:
      empty: stamina_0
      half: stamina_1
      full: stamina_2
    placeholder:
      value: '1.1'
      max-value: '2'